import { flattenStickyPromptText, pickStickyPromptRow } from "./sticky-prompt.ts";

const HOST_ATTR = "data-dsh-xtz-ui-sticky-host";
const SCROLLER_SELECTOR = "[data-conversation-scroll]";
const ROW_SELECTOR = '[data-chat-flow-kind="user"][data-chat-anchor-key]';
type StickyRow = { key: string; top: number; row: HTMLElement };
function reducedMotion(): boolean { return typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches; }
function textOf(row: HTMLElement): string { const root=row.querySelector("[data-time-hover-root]"); const stack=root?.querySelector(":scope > div"); return flattenStickyPromptText(stack?.lastElementChild?.textContent ?? ""); }
function rowsOf(scroller: HTMLElement): StickyRow[] { return Array.from(scroller.querySelectorAll<HTMLElement>(ROW_SELECTOR)).flatMap((row) => { const key=row.dataset.chatAnchorKey; return key ? [{key,top:row.getBoundingClientRect().top,row}] : []; }); }
function ensureHost(scroller: HTMLElement): HTMLElement { const found=scroller.querySelector<HTMLElement>(":scope > [data-dsh-xtz-ui-sticky-host]"); if(found)return found; const host=document.createElement("div"); host.setAttribute(HOST_ATTR,""); host.innerHTML='<div class="dshXtzStickyBar" hidden><button type="button" class="dshXtzStickyButton" aria-label="Pinned user prompt"><span class="dshXtzStickyText"></span></button></div>'; scroller.prepend(host); return host; }
function hide(host: HTMLElement): void { delete host.dataset.dshXtzUiStickyKey; const bar=host.querySelector<HTMLElement>(".dshXtzStickyBar"); if(!bar)return; bar.hidden=true; delete bar.dataset.dshXtzUiStickyVisible; const text=bar.querySelector<HTMLElement>(".dshXtzStickyText"); if(text)text.textContent=""; }
function render(scroller: HTMLElement): void { const rows=rowsOf(scroller); const host=scroller.querySelector<HTMLElement>(":scope > [data-dsh-xtz-ui-sticky-host]"); if(rows.length===0 && host===null)return; const actualHost=host ?? ensureHost(scroller); const bar=actualHost.querySelector<HTMLElement>(".dshXtzStickyBar"); const text=actualHost.querySelector<HTMLElement>(".dshXtzStickyText"); const button=actualHost.querySelector<HTMLButtonElement>(".dshXtzStickyButton"); if(!bar||!text||!button)return; const previous=actualHost.dataset.dshXtzUiStickyKey; const next=pickStickyPromptRow(rows,scroller.getBoundingClientRect().top,previous); const match=rows.find((item)=>item.key===next); if(!match||!next||textOf(match.row)===""){hide(actualHost);return;} text.textContent=textOf(match.row); actualHost.dataset.dshXtzUiStickyKey=next; bar.hidden=false; bar.dataset.dshXtzUiStickyVisible="1"; button.onclick=()=>{const row=rowsOf(scroller).find((item)=>item.key===next)?.row; row?.scrollIntoView({block:"start",behavior:reducedMotion()?"auto":"smooth"});}; }
function mutationTouchesConversation(record: MutationRecord): boolean { const target=record.target instanceof Element ? record.target : null; if(target?.closest("[data-dsh-xtz-ui-sticky-host]"))return false; for(const node of Array.from(record.addedNodes).concat(Array.from(record.removedNodes))){ if(node instanceof Element && node.closest("[data-dsh-xtz-ui-sticky-host]"))continue; return true; } return record.type==="characterData"; }
export function installStickyPrompt(): () => void { const frames=new WeakMap<HTMLElement,number>(); const refresh=(scroller:HTMLElement):void=>{if(frames.has(scroller))return; const frame=requestAnimationFrame(()=>{frames.delete(scroller);render(scroller);});frames.set(scroller,frame);}; const refreshAll=():void=>document.querySelectorAll<HTMLElement>(SCROLLER_SELECTOR).forEach(refresh); const onScroll=(event:Event):void=>{const target=event.target;if(target instanceof HTMLElement&&target.matches(SCROLLER_SELECTOR))refresh(target);}; const observer=new MutationObserver((records)=>{if(records.some(mutationTouchesConversation))refreshAll();}); document.addEventListener("scroll",onScroll,{capture:true,passive:true});window.addEventListener("resize",refreshAll);observer.observe(document.body,{childList:true,subtree:true,characterData:true});refreshAll(); return ()=>{document.removeEventListener("scroll",onScroll,true);window.removeEventListener("resize",refreshAll);observer.disconnect();for(const scroller of document.querySelectorAll<HTMLElement>(SCROLLER_SELECTOR)){const frame=frames.get(scroller);if(frame!==undefined)cancelAnimationFrame(frame);}document.querySelectorAll("[data-dsh-xtz-ui-sticky-host]").forEach((host)=>host.remove());}; }
